### ISSUE TITLE
Implement a retry policy

### ISSUE THREAD

**Issue by JanLenoch** [Kentico/cloud-sdk-swift#24]
Add a capability of dealing with transient network outages via the following retry policy:

* The retry policy should be **enabled** by default.
* The following should be configurable (preferably via the `DeliveryOptions` class):
  * enable/disable the retry logic (bool)
  * maximum amount of retry attempts (int)
* If specified, the Delivery client should retry in exponential retry intervals.
* The interval, in milliseconds, is always calculated as a power of the number 2. The exponent is the ordinal number of the next attempt. The result is then multiplied by 100. The order is one-based. For instance, the first retry attempt interval equals to (2<sup>2</sup> * 100), the second equals to (2<sup>3</sup> * 100), etc.
* When all retry attempts fail, the SDK should notify the client code about it, preferable via an exception.

Just a note: Platform- or framework-specific conventions have bigger priority than keeping the implementation the same in all our projects. Therefore, the above spec does not have to be followed along strictly, should there be a convention saying otherwise.

Sample implementation in other SDKs:
- [PHP](https://github.com/Kentico/delivery-sdk-php/commit/f402059504cdc2a23ec8bf368ffdc14e8426a2af)
- [.NET](https://github.com/Kentico/delivery-sdk-net/pull/115)
- [Java](https://github.com/Kentico/delivery-sdk-java/pull/54)

**Comment by JanLenoch** [comment]
Just a note: Platform- or framework-specific conventions have bigger priority than keeping the implementation the same in all our projects. Therefore, the above spec does not have to be followed along strictly, should there be a convention saying otherwise.

**Comment by Adoby7** [comment]
Hello, I want to contribute for this issue. However, once I modify anything in [DeliveryClient.swift](https://github.com/Kentico/cloud-sdk-swift/blob/master/KenticoCloud/Classes/DeliveryService/DeliveryClient.swift) (e.g adding an variable without any functional implementation), I cannot pass any testing case as the screenshot shown. I do not know why this problem happens. I have run `pod install` after I modify the `DeliveryClient.swift` file. Did I miss anything else?
![screenshot](https://user-images.githubusercontent.com/25312978/52412336-69c1dc00-2b19-11e9-958c-61aeebad7bfb.png)

**Comment by petrsvihlik** [comment]
Hi @Adoby7 , thanks for your interest. Two questions:
- Are you able to run the tests without modifying anything? 
- Can you share the repo/fork with your changes?

**Comment by petrsvihlik** [comment]
Cool.

@Adoby7, I've just sent you an invitation to the project. I'll be able to assign the issue to you once you accept it.

**Comment by Adoby7** [comment]
Hi @PavelJirik, I am sorry that I do have a lot of problems about authorizing to OAuth applications after enabling 2FA. May I quit this project and re-join it after I fix those authorization problems?

**Comment by Adoby7** [comment]
@petrsvihlik I am sorry that I left the project group because I had to disable 2FA for a while for OAuth applications. I have fixed that problem now. Could you send me the invitation again. Sorry for the inconvenience.

**Comment by petrsvihlik** [comment]
Done

**Comment by Adoby7** [comment]
Hi, I almost finish this issue, except for testing. I found that what I implemented in `DeliveryClient` is not reflected in the production code. I have used `pod update` and `pod install` but still doesn't work. Any suggestion?
